### ISSUE TITLE
[BUG] RunMacroText in securetemplates on PTR

### ISSUE THREAD

**Issue by artscout** [ClassicWoWCommunity/cata-classic-bugs#1488] opened 2024-09-10 12:12 UTC
#### 1.1. Description

Secure templates doesn't work on PTR as RunMacroText should be changed to C_Macro.RunMacroText

  #### 1.2. How to Reproduce
          Any addon that uses secure button to run macro, Vuhdo is perfect example
  #### 1.3  Source Material
![image](https://github.com/user-attachments/assets/86b00d43-9f8c-4cea-ac00-007062f564d2)

**Comment by raethkcj** [comment] 2024-09-10 14:14
Duplicate of https://github.com/Stanzilla/WoWUIBugs/issues/642

Fine to report UI issues here but as long as it's already reported, nice to keep it in one place

**Closed by raethkcj** 2024-09-10 14:14 UTC
Labels: Pending Approval, CATACLYSM
