### ISSUE TITLE
[BUG] Improved death strike bonus healing not always applied

### ISSUE THREAD

**Issue by mikihiso** [ClassicWoWCommunity/cata-classic-bugs#1535] opened 2024-11-02 00:16 UTC
#### 1.1. Description
Talent Improved death strike healing bonus doesn't affect base deathstrike healing
  #### 1.2. How to Reproduce
           1. Spec into blood and take Improved death strike talent 3/3
           2. Use Death strike on target dummy
           3. Look at it's healing, it will be 7% of max hp
           4. Spec out of blood to any other spec
           5. Use Death strike on target dummy
           6. Look at it's healing, it also will be 7% of max hp
#### 2.1. Description
Death strike when it chooses base healing should heal for 7% * 1.45 = 10.2%
  #### 2.2 Source Material
Talent description

**Comment by CharWS** [comment] 2024-11-02 01:23
duplicate of https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/898

**Closed** 2024-11-02 01:23 UTC
Labels: duplicate, Not a Bug, CATACLYSM
