### ISSUE TITLE
[BUG]Heart of Flame not spawning when dying during Ragnaros Heroic

### ISSUE THREAD

**Issue by Cyzz140** [ClassicWoWCommunity/cata-classic-bugs#1566] opened 2024-11-29 07:39 UTC
#### 1.1. Description
Heart of Flame is not lootable from Heroic Ragnaros if you die during the encounter (I died 7:00 minutes in) even if you got all the Smouldering Essences.
  #### 1.2. How to Reproduce
           1. Collect 250/250 Smouldering Essences
           2. Kill Ragnaros Heroic while the only person on this part of the chain
           3. Die during the encounter
           4. Get resurrected after the boss is dead
           5. Look for the item only to not find it anywhere
#### 2.1. Description
The item Heart of Flame should always appear on heroic difficulty regardless of dying.
  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Hotfixes/2011_Archive
[WoW Official Game Site (US)](http://us.battle.net/wow/en/blog/3019413) WoW Official Game Site (US) Patch 4.2 Hotfixes by [Zarhym](https://wowwiki-archive.fandom.com/wiki/Zarhym), Aug 4, 2011 4:51 PM PDT
Quote:
„Players should never get Rage of Ragnaros on Heroic difficulty. Rage of Ragnaros will only be given on normal difficulty if someone on the legendary quest line has 250 shards. Heart of Flame should always be given on Heroic difficulty, even if a player doesn’t have Rage of Ragnaros, but does have 250 shards.“

**Comment by Exesian** [comment] 2024-11-29 09:57
Any vod of this?

**Comment by Cyzz140** [comment] 2024-11-29 10:14
Not from my POV but from our fury warrior blaster this raid https://www.twitch.tv/videos/2313286231

Boss dies around 02:35:55 and you can see me dead in the party. After that, I looked for maybe 5 minutes before I turned on discord stream and some ppl tried to guide me without success. Reloading relogging etc didn’t help at all.

At 00:31:29 you could see the raid message that I completed the Smouldering Essences on the very first boss prior.

**Comment by Cyzz140** [comment] 2024-11-29 10:45
I got a ingame ticket response with a support article stating „Players on the quest still need to be alive to be eligible for the quest item.“

Case closed for me, sucks but apparently not a bug.

**Comment by Exesian** [comment] 2024-11-29 10:51
Yes, from what I can tell it seems to be supposed to give it as long as you're alive (Not dependant on the debuff like in normal), so you can get combat ressed. Going to see if I find any source material on this.

**Comment by Exesian** [comment] 2024-11-30 10:59
Found comments saying that you can't be dead on heroic to get the heart from 2012, so after the hotfix being linked to. Closing as not a bug.

**Closed by Exesian** 2024-11-30 10:59 UTC
Labels: Pending Approval, CATACLYSM, Dungeon or Raid
