### ISSUE TITLE
[BUG] Arena rating related achievements not being awarded

### ISSUE THREAD

**Issue by Vicinii** [ClassicWoWCommunity/cata-classic-bugs#1468] opened 2024-07-26 18:39 UTC
#### 1.2. probably needs more investigation since it looks like it only affects "newer" characters
reproduce
           1. reach 1550, 1750, 2000, 2200 in any bracket
           2. watch achievement log, theyre not there
  #### 1.3  Source Material
![image](https://github.com/user-attachments/assets/0330f9a5-a100-43ee-bbec-2b190e8d9b68)
![image](https://github.com/user-attachments/assets/d96e3eef-6f26-4ce7-a838-35b9dddf06f6)

#### 2.1. Description
Should get the achievement when certain rating in the bracket is reached

**Comment by JamminL** [comment] 2024-07-27 00:49
Duplicate of #https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/1447

**Closed by JamminL** 2024-07-27 00:49 UTC
Labels: Pending Approval, CATACLYSM
